name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install

    - name: Run tests with pytest
      run: |
        pytest -n auto --html=reports/report.html --self-contained-html
      continue-on-error: false

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: reports/report.html
